# Generated by Django 5.2.17 on 2026-09-19 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REWARD', 'Reward'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Adjustment')], max_length=10)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('transaction_type', 'REWARD')), models.Q(('amount__lt', 0), ('transaction_type', 'PURCHASE')), models.Q(('transaction_type', 'ADJUSTMENT'), models.Q(('amount', 0), _negated=True)), _connector='OR'), name='shop_transaction_valid_amount')],
            },
        ),
    ]
